######## Character Definitions ########################################################################

init -9997 python:
    # Define Jessie and Merry using the Char class
    Jes = Char( name="Jessie Avatar",
        abrev="jes",
        sex="male",
        color="#2F78CA",
        health=200,
        stam=150,
        strength=4,
        stomachHealth=0,
        acidStrength=0,
        stomachSize=0,
        size=1,
        acidResistance=2,
        acidFillRate=0,
        dexterity=8,
        constitution=5,
        lewdness=4,
        face="smile",
        profile="smile"
    )
    Sof = Char( name="Sofie Moon",
        abrev="sof",
        sex="female",
        color="#12C8EC",
        health=1000,
        stam=170,
        strength=700,
        stomachHealth=150,
        acidStrength=13,
        stomachSize=2,
        size=1,
        acidResistance=1,
        acidFillRate=0.07,
        dexterity=6,
        constitution=4,
        lewdness=3,
        face="smile",
        profile="smile"
    )
    Lea = Char( name="Leah Anagro",
        abrev="lea",
        sex="female",
        color="#00ff00",
        health=250,
        stam=125,
        strength=4,
        stomachHealth=250,
        acidStrength=25,
        stomachSize=1.5,
        size=0.85,
        acidResistance=4,
        acidFillRate=0.06,
        dexterity=6,
        constitution=5,
        lewdness=6,
        face="thinking"
    )
    Yul = Char( name="Yuliana Gomez",
        abrev="yul",
        sex="female",
        color="#9999ff",
        health=450,
        stam=500,
        strength=6,
        stomachHealth=350,
        acidStrength=30,
        stomachSize=5,
        size=0.7,
        acidResistance=10,
        acidFillRate=0.09,
        dexterity=17,
        constitution=50,
        lewdness=4,
    )
    Lil = Char( name="Lilly Oak",
        abrev="lil",
        sex="female",
        health=150,
        stam=120,
        strength=3,
        stomachHealth=500,
        acidStrength=50,
        stomachSize=3,
        size=0.8,
        acidResistance=3,
        acidFillRate=0.3,
        dexterity=8,
        constitution=8,
        lewdness=3,
        face="determined"
    )
    Lau = Char( name="Lauren Smith",
        abrev="lau",
        sex="female",
        health=250,
        stam=120,
        strength=5,
        stomachHealth=400,
        acidStrength=35,
        stomachSize=2,
        size=0.05,
        acidResistance=3,
        acidFillRate=0.3,
        dexterity=6,
        constitution=7,
        lewdness=2,
    )

define yul = Yul.c
# define jes = Jes.c # On hold for now
define sof = Sof.c
define lea = Lea.c
define lil = Lil.c
define esl = Esl.c
define lau = Lau.c