######## Character Definitions ########################################################################

init -9997 python:
    # Define Jessie and Merry using the Char class
    Jes = Char( name="Jessie Avatar",
        abrev="jes",
        sex="male",
        color="#2F78CA",
        health=200,
        stam=150,
        strength=4,
        stomachHealth=0,
        acidStrength=0,
        stomachSize=0,
        size=1,
        acidResistance=2,
        acidFillRate=0,
        dexterity=8,
        constitution=5,
        lewdness=4,
        face="smile",
        profile="smile"
    )
    Sof = Char( name="Sofie Moon",
        abrev="sof",
        sex="female",
        color="#12C8EC",
        health=1000,
        stam=170,
        strength=700,
        stomachHealth=150,
        acidStrength=13,
        stomachSize=2,
        size=1,
        acidResistance=1,
        acidFillRate=0.07,
        dexterity=6,
        constitution=4,
        lewdness=3,
        face="smile",
        profile="smile"
    )
    Lea = Char( name="Leah Anagro",
        abrev="lea",
        sex="female",
        color="#00ff00",
        health=250,
        stam=125,
        strength=4,
        stomachHealth=250,
        acidStrength=25,
        stomachSize=1.5,
        size=0.85,
        acidResistance=4,
        acidFillRate=0.06,
        dexterity=6,
        constitution=5,
        lewdness=6,
        face="thinking"
    )
    Fel = Char( name="Felicity Ferocity",
        sex="female",
        abrev="fel",
        color="#99ff99",
        health=300,
        stam=170,
        strength=7,
        stomachHealth=400,
        acidStrength=15,
        stomachSize=3,
        size=0.95,
        acidResistance=5,
        acidFillRate=0.1,
        dexterity=10,
        constitution=12,
        lewdness=1,
        face="smile chill"
    )
    Mer = Char( name="Merry Avatar",
        abrev="mer",
        sex="female",
        color="#00ff00",
        health=250,
        stam=120,
        strength=3,
        stomachHealth=250,
        acidStrength=20,
        stomachSize=3,
        size=1,
        acidResistance=3,
        acidFillRate=0.05,
        dexterity=6,
        constitution=7,
        lewdness=6,
        face="sass",
        profile="sass"
    )
    Ash = Char( name="Ash Grigori",
        abrev="ash",
        sex="female",
        color="#ff0000",
        health=1700,
        stam=1000,
        strength=1400,
        stomachHealth=1800,
        acidStrength=50,
        stomachSize=100,
        size=60,
        acidResistance=1000,
        acidFillRate=0.5,
        dexterity=1,
        constitution=40,
        lewdness=1,
        face="smile"
    )
    Yul = Char( name="Yuliana Gomez",
        abrev="yul",
        sex="female",
        color="#9999ff",
        health=450,
        stam=500,
        strength=6,
        stomachHealth=350,
        acidStrength=30,
        stomachSize=5,
        size=0.7,
        acidResistance=10,
        acidFillRate=0.09,
        dexterity=17,
        constitution=50,
        lewdness=4,
    )
    Ste = Char( name="Stephanie Avianna",
        abrev="ste",
        sex="female",
        health=150,
        stam=150,
        strength=3,
        stomachHealth=360,
        acidStrength=3,
        stomachSize=1.5,
        size=0.65,
        acidResistance=0.5,
        acidFillRate=0.08,
        dexterity=20,
        constitution=3,
        lewdness=2,
    )
    Ast = Char( name="Astaria Oz Blair",
        abrev="ast",
        sex="female",
        color="#00ff00",
        health=250,
        stam=120,
        strength=3,
        stomachHealth=250,
        acidStrength=20,
        stomachSize=2,
        size=1,
        acidResistance=1,
        acidFillRate=0.05,
        dexterity=5,
        constitution=3,
        lewdness=3,
    )
    Sag = Char( name="Sage Oz Blair",
        abrev="sag",
        sex="female",
        color="#00ff00",
        health=175,
        stam=130,
        strength=8,
        stomachHealth=180,
        acidStrength=15,
        stomachSize=3,
        size=1,
        acidResistance=1,
        acidFillRate=0.04,
        dexterity=1,
        constitution=2,
        lewdness=1,
    )
    Lil = Char( name="Lilly Oak",
        abrev="lil",
        sex="female",
        health=150,
        stam=120,
        strength=3,
        stomachHealth=500,
        acidStrength=50,
        stomachSize=3,
        size=0.8,
        acidResistance=3,
        acidFillRate=0.3,
        dexterity=8,
        constitution=8,
        lewdness=3,
        face="determined"
    )
    Esl = Char( name="Esel Granger",
        abrev="esl",
        sex="female",
        health=350,
        stam=135,
        strength=10,
        stomachHealth=600,
        acidStrength=17,
        stomachSize=2,
        size=3.0,
        acidResistance=3,
        acidFillRate=0.08,
        dexterity=8,
        constitution=20,
        lewdness=1,
        face="smile"
    )
    Pen = Char( name="Penelope Danse",
        abrev="pen",
        sex="female",
        health=250,
        stam=120,
        strength=5,
        stomachHealth=900,
        acidStrength=10,
        stomachSize=2,
        size=0.05,
        acidResistance=3,
        acidFillRate=0.05,
        dexterity=6,
        constitution=7,
        lewdness=2,
    )
    Bth = Char( name="Beth Dista",
        abrev="bth",
        sex="female",
        health=250,
        stam=120,
        strength=5,
        stomachHealth=255,
        acidStrength=17,
        stomachSize=2,
        size=0.05,
        acidResistance=3,
        acidFillRate=0.03,
        dexterity=6,
        constitution=7,
        lewdness=2,
    )
    Lau = Char( name="Lauren Smith",
        abrev="lau",
        sex="female",
        health=250,
        stam=120,
        strength=5,
        stomachHealth=400,
        acidStrength=35,
        stomachSize=2,
        size=0.05,
        acidResistance=3,
        acidFillRate=0.3,
        dexterity=6,
        constitution=7,
        lewdness=2,
    )
    Glo = Char( name="Gloria Marques",
        abrev="glo",
        sex="female",
        health=250,
        stam=120,
        strength=5,
        stomachHealth=300,
        acidStrength=15,
        stomachSize=2,
        size=0.05,
        acidResistance=3,
        acidFillRate=0.05,
        dexterity=6,
        constitution=7,
        lewdness=2,
    )
    Rei = Char( name="Reiss Juno",
        abrev="rei",
        sex="female",
        health=250,
        stam=120,
        strength=5,
        stomachHealth=150,
        acidStrength=4,
        stomachSize=2,
        size=0.05,
        acidResistance=3,
        acidFillRate=0.01,
        dexterity=6,
        constitution=7,
        lewdness=2,
    )
    Rox = Char( name="Roxy Mercury",
        abrev="rox",
        sex="female",
        health=250,
        stam=120,
        strength=5,
        stomachHealth=250,
        acidStrength=22,
        stomachSize=2,
        size=1,
        acidResistance=3,
        acidFillRate=0.05,
        dexterity=6,
        constitution=7,
        lewdness=2,
    )
    Jet = Char( name="Jett Vespa",
        abrev="jet",
        sex="female",
        health=250,
        stam=120,
        strength=5,
        stomachHealth=315,
        acidStrength=20,
        stomachSize=2,
        size=4,
        acidResistance=3,
        acidFillRate=0.05,
        dexterity=6,
        constitution=7,
        lewdness=2,
    )
    JetBee = Char( name="Jett Vespa",
        abrev="jetBee",
        sex="female",
        health=250,
        stam=120,
        strength=5,
        stomachHealth=600,
        acidStrength=25,
        stomachSize=2,
        size=3,
        acidResistance=3,
        acidFillRate=0.05,
        dexterity=6,
        constitution=7,
        lewdness=2,
    )
    Gai = Char( name="Gaia Nepenthes",
        abrev="gaia",
        sex="female",
        health=250,
        stam=120,
        strength=5,
        stomachHealth=200,
        acidStrength=17,
        stomachSize=2,
        size=1,
        acidResistance=3,
        acidFillRate=0.06,
        dexterity=6,
        constitution=7,
        lewdness=2,
    )
    Lna = Char( name="Lillianna Sylphann",
        abrev="lna",
        sex="female",
        health=250,
        stam=120,
        strength=5,
        stomachHealth=275,
        acidStrength=17,
        stomachSize=2,
        size=1,
        acidResistance=3,
        acidFillRate=0.05,
        dexterity=6,
        constitution=7,
        lewdness=2,
    )
    Kor = Char( name="Korbin Moon",
        abrev="kor",
        sex="male",
        health=250,
        stam=120,
        strength=5,
        stomachHealth=0,
        acidStrength=0,
        stomachSize=0,
        size=1,
        acidResistance=3,
        acidFillRate=0,
        dexterity=6,
        constitution=7,
        lewdness=2,
        face="smug"
    )

define yul = Yul.c
# define jes = Jes.c # On hold for now
define sof = Sof.c
define lea = Lea.c
define fel = Fel.c
define mer = Mer.c
define ash = Ash.c
define ste = Ste.c
define ast = Ast.c
define sag = Sag.c
define lil = Lil.c
define esl = Esl.c
define pen = Pen.c
define bth = Bth.c
define lau = Lau.c
define glo = Glo.c
define rei = Rei.c
define rox = Rox.c
define jet = Jet.c
define gai = Gai.c
define lna = Lna.c
define kor = Kor.c